### ISSUE TITLE
Code the basic stats for melee enemy

### ISSUE THREAD

**Issue by bach-truong** [UQdeco2800/2022-studio-2#10]
# **Description**
Code the basic stats for the melee enemy which include the health, attack power, movement speed, etc. The relevant stats that existed are determined by the mechanism of the game.
**Feature:** [Enemies](#3)

 # **Milestone**

- [x] Code the health of the melee enemy
- [x] Code the power of the melee enemy
- [x] Code the movement speed of melee enemy

# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2022-studio-2/wiki/Enemies)
 
# **Member**
- Bach Truong (@bach-truong) (Bach Truong)

**Comment by c-alsop** [comment]
This task has been completed.
