### ISSUE TITLE
Implement enemy death condition

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#119]
# **Description**
**Task:** Ensure that when the enemy's health reaches 0, that the enemy dies.
**Feature:** #118 

This is a collaboration ticket between Team 03 and Team 04. Team 04 is developing an attack function to reduce the health of the enemy. Once the enemy health reaches 0. Team 03 and Team 04 must work together to ensure that the enemy dies in a suitable way.

# **Milestones**
List of steps that need to be completed for this task.
- [x] When health = 0, the enemy dies (Sept. 09)

# **Members**
Team 03

**Comment by LachlanBenson** [comment]
@bach-truong Please see that Team 04 has successfully implemented the enemy death condition.

We needed to make some modifications to the Entity dispose function to prevent the atlas animations from breaking upon killing one enemy.

![image](https://user-images.githubusercontent.com/109946739/189251442-16e72fce-06ac-47a9-ac09-a694ae3c2338.png)

**Comment by bach-truong** [comment]
Yeah Thanks, @LachlanBenson . Before, we only have a way to let it die by defining the dead flag and putting it in the update. It also worked but we haven't encountered the atlas issues so great job.

`/**
   * Perform an update on all components. This is called by the entity service and should not be
   * called manually.
   */
  public void update() {
    if (!enabled) {
      return;
    }
    if (isDead) {
      dispose();
    }
    for (Component component : createdComponents) {
      component.triggerUpdate();
    }
  }`
