### ISSUE TITLE
[FEATURE] Augmenting the capabilities of combat items

### ISSUE THREAD

**Issue by NishaVashist0** [UQdeco2800/2022-studio-2#150]
# **Description**

For the third sprint, our team will be focussing upon the capabilities associated with equipping each weapon. In previous sprints within the configuration of each weapon unique statistics were assigned this includes weight, materials, cooldown and damage. These statistics have an impact on the game play. For example, the weight of the weapon will impact the player's speed and ability to move around the environment. Hence, the focus of this sprint centres around implementing the associated effects of our weapons in the game play. As a result this also includes implementing the different effects buffs  have on each weapon.

Due to the collective studio decision to remove level 3 from the original gameplay, the addition of level 3 weapons was also removed. Having said this, we will be animating all the weapons created within the previous sprints and the visualisation of the argumentation of the weapon. Additionally, we will be creating a new bow and arrow weapon which will require a new projectile function to be implemented.

Lastly, the functionality and the animation will work coherently with each other. This means the functionally equipped weapon will play its animation. 

This feature is important to the game, as it impacts the players strength to attack enemies and progress through the game.It is hoped it encourages the player to keep playing. 

## SubFeature/component 
_Note: JUnit testing and User Testing will be done throughout the sprint and therefore is a given even though not specifically mentioned within the sub features._

- Level 2 weapon creation:
  - New bow and arrow plunger

- Animation sprite created for player:
  - Dagger 
  - PVC Pipe  
  - Trident 
  - Plunger
  - Sword 

- Weapon appearance into player hand
  - For all animated weapons listed above
- Weapon drop function
  - Work with the crafting team to implement this code for material drops
- Attack cooldown duration
  - Can’t use weapon for a set period of a time after swinging 
- Implementing the associated animation with the equipped weapon
- Buff and debuff stats impacting the player’s weapon if equipped
- Buff visual overlays and animation
- Projectile implementation 
  - Specific for the bow plunger weapon which will shoot plunger arrows

# **Dependencies**

- Player team - Ensure the overlay work in line with the player team. 
- Skill team - Ensure the overlay of elements such as skills and buff/debuff are the same 
- Crafting team - The interaction of dropping a weapon and how it impacts its materials. 

# **Milestones**

- [x] #180 (Sept. 25)
  - @PurrplePandaa 
- [x] #178  (Oct. 26)
  - @PurrplePandaa 
  - @NishaVashist0
  - @madifeddema 
- [x] #181 (Oct. 02) subjected to change
  - @PurrplePandaa 
  - @NishaVashist0 
  - @madifeddema 
- [x] #120 (Sept. xx)
  - @LachlanBenson 
- [x] #201 (Sept. xx)
  - @eugene2341 
- [x] #200  (Sept. xx)
  - @NishaVashist0 
  - @eugene2341 
  - @LachlanBenson 
- [x] #203 (Oct. xx)
  - @eugene2341
- [x]  #202 (Oct. xx)
  - @eugene2341 
  - @LachlanBenson 

**Completion Deadline:** 4th of October 

# **Extras/ Considerations for next Sprint:**
- Buffs/Debuffs:
  - Design and functionality of icon timer at the bottom of the screen

# **Documentation**
- [Combat Items Wiki](https://github.com/UQdeco2800/2022-studio-2/wiki/Combat-Items)

# **Members**

 - Lachlan Benson, @LachlanBenson
- Caleb Ang, @PurrplePandaa
- Nisha Vashist, @NishaVashist0
- Madi Feddema, @madifeddema
- Eugene Chong, @eugene2341

**Comment by madifeddema** [comment]
@PurrplePandaa @NishaVashist0 and @madifeddema we've completed all animations for weapons and buffs on weapons
