### ISSUE TITLE
<Bug> Unable to successfully transition to Level 2

### ISSUE THREAD

**Issue by IshaanM8** [UQdeco2800/2022-studio-2#186]
## Description
Once the player positions themselves over the plug and "enters " the next level, the graphics don't seem to be properly loaded which in turn crashes the game when players have transitioned to Underground GameArea.

## How To Reproduce
Steps to reproduce the behaviour:
1. Move around map to find the plug
2. Once spotted, move towards the centre of the plug
3. Once near the middle of the plug, press enter to reach the underground area

## Expected Behaviour
Once player has entered the underground game area, it should not crash the game, it should load the graphics properly and the player should be able to interact with objects, move around, fight, use skills and all such features like they were able to on the first level.

## Screenshots
![image](https://user-images.githubusercontent.com/109838347/190939341-4e0428ff-1575-426a-8158-04fcfba3843e.png)

## Additional Context
It varies from time to time depending on the actions the user has taken on when the application crashes, could be instanly or you could play the game for 10 to 15 seconds before it crashes.

## Temporary Fix
Upon removing the sprites that are not loading from the code file, the map loads fine and doesn't crash.

**Comment by IsaacGraham128** [comment]
Hey @IshaanM8, I think with my new code alterations I have fixed this bug. Through my testing I did not notice any black boxes. I believe the issue lied with the disposal and reuse of the prior map object.

**Comment by IshaanM8** [comment]
Yes, transition seems smooth and crashes have been non-existant! Much appreciated 👍🏼
