### ISSUE TITLE
Crafting Menu Display

### ISSUE THREAD

**Issue by lyphng** [UQdeco2800/2022-studio-2#20]
# **Description**
**Task:** Display with the different items that can be crafted (sword) and show materials 
**Feature:** Crafting system #4 

The task is to display the items that are available to be crafted at this stage in the crafting UI. Currently there is only a sword, which will be crafted using wood and steel. This will be displayed on the left side of the crafting menu and the individual item crafting feature will be displayed on the right side of the menu. The individual crafting feature will have the item to be crafted (sword) displayed as well as the items it needs (wood and steel). At this stage, it is assumed that the user has unlimited wood and steel. When the crafting table is selected, there will be a button event handler that displays the menu. This will display the sword as being available to be crafted as well as its individual crafting menu since this is the only item. A bigger image of the sword will be displayed as well as the image of wood and steel at the bottom. Underneath this will be the craft button that handles the crafting of the item and is for Task Ticket #19.
 
## **Example**
- **Crafting feature **
![image](https://user-images.githubusercontent.com/110011999/184530919-ceeba2a3-bdb4-462a-931c-3adc38580ea5.png)

# **Dependencies**
- The map where the crafting table is located needs to be implemented.
- The visual design of the crafting table needs to be done so it can be selected
- The visual design of the crafting UI as well as the sword, wood and steel need to be done so it can be displayed.

# **Milestones**
List of steps that need to be completed for this task.
- Adding a button to the map so the crafting menu can be opened (Aug. 19).
- Event handler to display the crafting menu (Aug. 23).
- Adding the craft button to the menu (Aug. 23).
- Display the sword, wood and steel (Aug 28).
 
**Completion Deadline:** Aug. 28
 
# **Documentation**
- Crafting System Layout (../wiki/Crafting-System-Layout)
 
# **Member**
- Ly Phung (lyphng) (Ly Phung)

**Comment by rkoll55** [comment]
Display has been created and is accessible in game
