### ISSUE TITLE
[Collaboration] Crafting menu items resolution

### ISSUE THREAD

**Issue by PurrplePandaa** [UQdeco2800/2022-studio-2#213]
# **Description**
**Task:** 
[Crafting Menu items](#182)
**Feature:** 
[Augmenting the capabilities of combat items](#150) 
[Optimisation of Crafting Functionality and Additional Features](#151)
 
# **Dependencies**
Below are the following dependencies for the following task ticket.
- [x] Weapon reimaged size
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Resize of images to reduce invisible white space (Sept. 24)
 
**Completion Deadline:** Sept. 24
 
# **Member**
- Caleb Ang (@PurrplePandaa) (Caleb Ang)
- Ly Phung (@lyphng) (Ly Phung)
- Enoe (Jolo) Gapusan (@jgapusan) (Jolo Gapusan)

**Comment by PurrplePandaa** [comment]
![image](https://user-images.githubusercontent.com/109809229/192084772-88ae02e6-d915-4f3a-9cae-08ae45f2d349.png)
![image](https://user-images.githubusercontent.com/109809229/192084783-aea529df-ea12-413e-8109-abd1625126c5.png)
![image](https://user-images.githubusercontent.com/109809229/192084789-ae4d4113-00fe-4258-8bef-6a53e5ccb9fc.png)
![image](https://user-images.githubusercontent.com/109809229/192084798-a4dd8c21-e12d-4192-9354-3d89342917d4.png)
![image](https://user-images.githubusercontent.com/109809229/192084801-6783c657-ba29-4fcd-a299-b54023ae6a23.png)
![image](https://user-images.githubusercontent.com/109809229/192084808-ea73cbbc-5ce3-4d74-8457-7057765ff3c1.png)
![image](https://user-images.githubusercontent.com/109809229/192084814-171745dc-60a6-492b-80f6-becdf758a9b9.png)
![image](https://user-images.githubusercontent.com/109809229/192084826-ec18edeb-e9f9-423c-9cd0-3431a74c5556.png)
![image](https://user-images.githubusercontent.com/109809229/192084831-408b5d0d-02ed-44f0-b88f-f192d7b31419.png)
![image](https://user-images.githubusercontent.com/109809229/192084835-8ef1ea72-c2f8-4ac6-9967-b22c6a39f205.png)
![image](https://user-images.githubusercontent.com/109809229/192084844-e53d312f-9782-46dc-889b-c3e0603408b6.png)
![image](https://user-images.githubusercontent.com/109809229/192084848-267f192c-a3b7-43a1-af40-acfa9e63dc3f.png)
![image](https://user-images.githubusercontent.com/109809229/192084849-e2aa3596-f0da-4674-99e8-6df9aa6e42e8.png)
![image](https://user-images.githubusercontent.com/109809229/192084854-4bb90a6e-d73b-4a2b-886f-583fba4a4b4c.png)
![image](https://user-images.githubusercontent.com/109809229/192084859-9bc4c2c4-81ff-4577-b1a4-ce17088ab41e.png)
![image](https://user-images.githubusercontent.com/109809229/192084872-252adeb9-96be-4dbb-a052-72b8feede4ba.png)

**Comment by PurrplePandaa** [comment]
Prior conversations include:
![image](https://user-images.githubusercontent.com/109809229/192084964-7844a8f6-c611-4cdc-bd71-9be1eeb2ff73.png)
![image](https://user-images.githubusercontent.com/109809229/192084993-ecb41c9e-1784-4ca7-b947-441a059ea599.png)
![image](https://user-images.githubusercontent.com/109809229/192084999-4fb84271-1d3f-40f6-8926-cb3f609bb563.png)
![image](https://user-images.githubusercontent.com/109809229/192085024-2ce8117d-1bbd-4cac-80e8-f79296b45ed7.png)

**Comment by PurrplePandaa** [comment]
@lyphng @jgapusan I've merged out the new files into main but if you want to download the files you can do so by clicking - 
[weaponsWhiteSpaceRemoval.zip](https://github.com/UQdeco2800/2022-studio-2/files/9638131/weaponsWhiteSpaceRemoval.zip)

I have also inserted the .Psd and the .pixil files for you guys to modify as well! lmk if there are any other issues! Please working with y'alls.
:)

**Comment by lyphng** [comment]
awesome job @PurrplePandaa !

**Comment by PurrplePandaa** [comment]
Thanks @lyphng !!

**Comment by jgapusan** [comment]
hey @PurrplePandaa we're having issues with the sizing of the images within the crafting table inventory and we think it may be caused by your image files.

**Comment by lyphng** [comment]
Just adding on, would you guys b able to crop ur images so there's not a lot of white space around it or will
it mess up stuff?

**Comment by PurrplePandaa** [comment]
Yeah I can do that but I'll needa have a look at it first. What size did you say you wanted to make the boxses again? Like for the crafting, I'll have a look at the changes. Also which images did you say was buggy?

**Comment by lyphng** [comment]
All the weapon images if possible, it's not buggy just that the empty space is interfering with hitboxes

**Comment by PurrplePandaa** [comment]
Wait idk what's wrong with the image rn though, just waiting for Jolo cuz I needa replicate the issue for me to fix it. I think the solution would prolly just be to enlarge the image size so that it reduces the free transparent space on the canvas.

**Comment by lyphng** [comment]
Yeah that's basically it. Just have the same 32x32 canvas size but the weapon takes up most of the space.

**Comment by jgapusan** [comment]
erm should be 40 x 40 pixels i think, just have a look at this pixil file rq 
![lvl2craftingmenu](https://user-images.githubusercontent.com/110016922/192145334-ffcc7485-4154-45bf-96bb-170676f755e3.png)

**Comment by PurrplePandaa** [comment]
So you wanted me to make all the weapons 40x40? @jgapusan

**Comment by jgapusan** [comment]
Nah so the boxes were done by making them 40x40 pix but would be nice if you could make them 32x32pix.
I manually resized the images so they fit inside my crafting inventory. So it's not really dynamic iyk what I mean.
But you just need to delete the whitespace on the canvas by resizing the canvas so that the weapon will be touching
the edges of the canvas. It should be a different size for each weapon since each weapon is of a different size. @PurrplePandaa

**Comment by PurrplePandaa** [comment]
So wait something like this?
![image](https://user-images.githubusercontent.com/109809229/192145459-6598ed1d-91f3-4794-a01c-51b223af7a0a.png)

**Comment by jgapusan** [comment]
Yeah so center it and then slowly resize the canvas so the white space on the edge slowly decreases.

**Comment by PurrplePandaa** [comment]
It kinda looks scuffed though when I do it.
![image](https://user-images.githubusercontent.com/109809229/192145558-12b1b7d2-f9d8-4b08-979e-2e7a3ac0d164.png)

**Comment by jgapusan** [comment]
Yeah so you needa unclick the 'resize contents' box and then try that, it won't distort.

**Comment by PurrplePandaa** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/109809229/192145658-25c6489e-68e1-4575-8c59-789a582c8bc1.png)

**Comment by jgapusan** [comment]
Yeah perfect, now do that for the rest would be great!

**Comment by lyphng** [comment]
awesome job @PurrplePandaa !

**Comment by jgapusan** [comment]
> Pleasure working with y'alls. :)
wish i could say the same honestly

**Comment by PurrplePandaa** [comment]
Thanks @lyphng ! 💩 @jgapusan
