### ISSUE TITLE
[Collab] Bug fixes for animation disposal with InventoryComponent

### ISSUE THREAD

**Issue by eugene2341** [UQdeco2800/2022-studio-2#225]
# **Description**
**Task:** 
[Implement unequip for weapon/armour](#188)
**Feature:** 
[Inventory interactions and refinements] (#149 )
 
# **Milestones**
List of things completed for this collaboration
- [x] Fix drop weapon bug where animation is not properly disposed and retains on player. (2nd October)
- [x] Fix unequip weapon bug where animation becomes a static image on the map. (2nd October)
 
**Completion Date:** October 2nd
 
# **Members**
- Li-Sung Ou (@PeterOu8) (Secret Agent Randy Beans#6754)
- Lachlan Benson (@LachlanBenson ) (Lachlan.Benson#4926)
- Eugene Chong (@eugene2341 ) (gene#0005)

**Comment by LachlanBenson** [comment]
@PeterOu8 thanks for working with us on this one!
