### ISSUE TITLE
[Collab Bug] Attack animation pauses upon game entering pause state

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#226]
## Description
When the game enters a pause state (pause menu, inventory, crafting), all animations in the game are paused as intended. However, upon closing the menus, the weapon attack animations are permanently stuck and do not resume.

## How To Reproduce
Steps to reproduce the behaviour:
1. Add a weapon to your inventory through the code for testing purposes
2. Equip the weapon
3. Close inventory
4. Attack animation then works
5. Open inventory again
6. Close inventory
7. Weapon attack animation now does not play

## Expected Behaviour
Attack animation should continue working despite menus opening/closing.

## Temporary Fix
No temporary fixes known.

**Comment by LachlanBenson** [comment]
@kurt-553 as discussed are you able to assist us with finding the cause of this bug?

**Comment by kurt-553** [comment]
@LachlanBenson helped immensely diagnosing a problem and how to go about fixing it

**Comment by LachlanBenson** [comment]
@kurt-553 thanks for the assist!
