### ISSUE TITLE
Logging for combatitems

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#227]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

Helpful logging information needs to be implemented to assist with game debugging in the future. This applies for the attack function as well as all related combat items functions,

## **Example (optional)**
- When attack is called, shows how much attack damage is done in the log.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Confirming logging messages (Oct. 3)
- [x] Implement logging (Oct. 3)

# **Member**
- Madi Feddema @madifeddema

**Comment by madifeddema** [comment]
All done! add the logger information in :)
