### ISSUE TITLE
[Collaboration] Item Pickup

### ISSUE THREAD

**Issue by eugene2341** [UQdeco2800/2022-studio-2#233]
# **Description**
**Related Tasks:** Update of [Weapon Pickup Functionality]#108 

When the player is in contact with an entity that implements `ItemPickupComponent`, remove the item from the current gameArea (be it `ForestGameArea` or `UndergroundGameArea`) .

The class is heavily based on the old [WeaponPickupComponent](https://github.com/UQdeco2800/2022-studio-2/wiki/Weapon-Pickup-Function), which initially allows weapons to be picked up from the map and put into the inventory. However, since the pickup functionality is useful, @PeterOu8 created a `ItemPickupComponent` which allows not just weapons, but all items that implement this to be picked up (such as materials). The code is the same, with some naming changes.

@eugene2341 have since deleted the old [WeaponPickupComponent](https://github.com/UQdeco2800/2022-studio-2/wiki/Weapon-Pickup-Function), and made all the weapons implement the `ItemPickupComponent`, as there is no need for them to be treated differently as any other entity that can be picked up, unlike auras, which uses [AuraPickupComponent](https://github.com/UQdeco2800/2022-studio-2/wiki/Aura-Pickup-and-Application) that extends the `ItemPickupComponent`.

Towards the end of Sprint 3, @eugene2341 added few extra lines of code to check for the current `GameArea`, then remove the item on that game area. Prior to this, the item pickup function only works on `ForestGameArea`
```Java
 if (ServiceLocator.getGameArea() instanceof ForestGameArea) {
                ((ForestGameArea) ServiceLocator.getGameArea()).removeItemOnMap(entityOfComponent);
            }
 else if (ServiceLocator.getGameArea() instanceof UndergroundGameArea){
                ((UndergroundGameArea) ServiceLocator.getGameArea()).removeItemOnMap(entityOfComponent);
            }
```

**Completion Date:** September 21

# **Members**
- Li-Sung Ou (@PeterOu8) (Secret Agent Randy Beans#6754)
- Eugene Chong (@eugene2341 ) (gene#0005)

**Comment by PeterOu8** [comment]
It was nice working with you!! 8====D

**Comment by eugene2341** [comment]
> It was nice working with you!! 8====D

Be more realistic. 
8==D
