### ISSUE TITLE
[Collaboration] Crafting System Sounds

### ISSUE THREAD

**Issue by jgapusan** [UQdeco2800/2022-studio-2#249]
**Feature:** [Optimisation and Enhancement of Crafting System + Additional Features](#247)

# Description
Design and implement crafting system sounds and sounds for other related features.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] General Concept/Design (Oct 9th)
- [x] User Testing (Oct 10th)
- [x] Updating Design Based on Feedback (Oct 11th)
- [x] Final Iteration/Implementation (Oct 12th)
 
**Completion Deadline:** Oct 12th
 
# **Documentation**
- [Crafting Sounds](https://github.com/UQdeco2800/2022-studio-2/wiki/Crafting-Sounds-Audio-Assets-Design)
 
# **Members**
- Enoe (Jolo) Gapusan (@jgapusan)
- Ly Phung (@lyphng)
- Hazeem bin Suffain (@uq-haze)

**Comment by jgapusan** [comment]
@uq-haze how did you want to include your voice in our crafting sounds?

**Comment by uq-haze** [comment]
@jgapusan maybe when the player crafts a weapon, there will be a voice over that says 'weapon crafted' or something along those lines

**Comment by jgapusan** [comment]
@uq-haze sounds good! if you could send thru a few variations for user testing asap that’d be great - have fun w it haha

**Comment by jgapusan** [comment]
for reference these are the sound FX for the weapon crafted sound 
https://freesound.org/people/ash_rez/sounds/518888/
https://freesound.org/people/cameronmusic/sounds/138410/
https://freesound.org/people/axilirate/sounds/592346/

**Comment by uq-haze** [comment]
aight let me record some variation

**Comment by uq-haze** [comment]
[Weapon Crafted Variants.zip](https://github.com/UQdeco2800/2022-studio-2/files/9738517/Weapon.Crafted.Variants.zip)
@jgapusan alright here are the voice lines
cringe to your hearts content XD

**Comment by jgapusan** [comment]
oh my it’s beautiful >_<

just last request if you edit the file so the voice plays immediately, the milliseconds of gap causes a weird disconnect from the popup and the sound ;-;

no rush it wont affect programming or any of that so u have til end of sprint for it :D in fact once my user testing is complete i’ll let you know which one in particular will be used - save you some work :D thx tho everything sounds great so far

**Comment by uq-haze** [comment]
alright will do! Let me know when you've gotten user testing results and ill edit the voice files

**Comment by lyphng** [comment]
It's been implemented! You guys can view the details in these two commits:
https://github.com/UQdeco2800/2022-studio-2/commit/5eb738ff2a53e81fc9ffc57e49b392a46b0d2287
https://github.com/UQdeco2800/2022-studio-2/commit/5d736ea33ef70bd2e3901f34a5c7e730f003d97c
