### ISSUE TITLE
[Task] Tutorial Popups

### ISSUE THREAD

**Issue by jgapusan** [UQdeco2800/2022-studio-2#250]
**Feature:** [Optimisation and Enhancement of Crafting System + Additional Features](#247)

# Description
Design and implement tutorial popups for the crafting system. When the player opens the crafting menu for the first time, they will be greeted with a tutorial on how to craft. If they exit the tutorial in the middle, it will restart since the player may have forgotten where they were up to. The tutorial will step the player through how to select the first and second material as well as how to craft a weapon using them. The tutorial will also give the user the wood and rubber materials in order for them to craft a plunger as their starting weapon. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] General Concept/Design (Oct 9th)
- [x] User Testing (Oct 10th)
- [x] Updating Design Based on Feedback (Oct 11th)
- [x] Final Iteration/Implementation (Oct 12th)
 
**Completion Deadline:** Oct 12th
 
# **Documentation**
- TBC
 
# **Member**
- Enoe (Jolo) Gapusan (@jgapusan)
- Ly Phung (@lyphng)

**Comment by lyphng** [comment]
commit: https://github.com/UQdeco2800/2022-studio-2/commit/229c14bd248fa9f90d8cdc501c35512a4e26ddde
