### ISSUE TITLE
[Collaboration] Weapon Statistics in Player Guide

### ISSUE THREAD

**Issue by jgapusan** [UQdeco2800/2022-studio-2#286]
**Feature:** [Optimisation and Enhancement of Crafting System + Additional Features](#247)

# Description
Implement weapon statistics in player guide screen.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] General Concept/Design (Oct 9th)
- [x] User Testing (Oct 10th)
- [x] Updating Design Based on Feedback (Oct 11th)
- [x] Final Iteration/Implementation (Oct 12th)
 
**Completion Deadline:** Oct 12th
 
# **Documentation**
TBA
 
# **Members**
- Enoe (Jolo) Gapusan (@jgapusan)
- Lachlan Benson (@LachlanBenson)

**Comment by jgapusan** [comment]
hey @LachlanBenson where would i be able to find the most up to date statistics for all your weapons?

**Comment by LachlanBenson** [comment]
@jgapusan You should be able to find the most up to date weapon statistics in 
source/core/assets/configs/Weapons.json

This contains all of the statistics you should require for the player guide.

Is this what you were after?

**Comment by jgapusan** [comment]
@LachlanBenson yea that looks about right!

![image](https://user-images.githubusercontent.com/110016922/196027197-00875a31-4b6e-42c6-8bd7-1e09736a9469.png)
![image](https://user-images.githubusercontent.com/110016922/196027200-8bbca9eb-e09d-4fa0-bb26-5355c0cfd989.png)

i didn't include craftable information but does this look ok ?

**Comment by LachlanBenson** [comment]
I think this should be fine because there is 'how to craft' features implemented into the crafting menu already so we don't really have a need to double up on those instructions here.

Thanks for implementing this for us!

**Comment by jgapusan** [comment]
no worries thx for your help !
