### ISSUE TITLE
<Collaboration> Restrict menu to maximum one can be open at a time

### ISSUE THREAD

**Issue by PeterOu8** [UQdeco2800/2022-studio-2#292]
# **Description**
**Task:** [Restrict menu to maximum one can be open at a time](#).
**Feature:** [Implement functionality to enhance UX](#291)

Currently, the game allows the player to open up more than 1 type of menu. To avoid this, we will implement a feature that will only allow one menu at a time to be opened.

# **Documentation**
- [Main description of feature](../wiki/Inventory)

**Completion Date:* October 14

# **Members**
- Li-Sung Ou (@PeterOu8) (Li-Sung Ou)

**Comment by PeterOu8** [comment]
@lyphng @jgapusan Will you guys be able to work on this feature with me?

**Comment by lyphng** [comment]
that sounds great peter sure thing!

**Comment by jgapusan** [comment]
hey @PeterOu8 what did you have in mind with this particular task?

**Comment by PeterOu8** [comment]
I am thinking of setting a flag to determine what menu is currently opened and handle it from there

**Comment by jgapusan** [comment]
that seems like the best way to go about it, are you alright to implement that yourself ?

**Comment by PeterOu8** [comment]
> that seems like the best way to go about it, are you alright to implement that yourself ?

yeah sure

**Comment by LachlanBenson** [comment]
@PeterOu8 just flagging an incomplete part of this task

currently if you press "Q" while away from a crafting table, it then prevents the user from opening their inventory using "I"

if you press Q again, then you can use the inventory as usual

seems like a toggle flag/switch is being toggled when it shouldn't be.

Maybe need to add a condition for it only toggling the flag if the craftingtable is actually activated?

**Comment by PeterOu8** [comment]
> 

Thanks for the notification, I will put the flag handling in the openingCraftingMenu function

**Comment by LachlanBenson** [comment]
@PeterOu8 confirmed issue is resolved
