### ISSUE TITLE
<Collaboration> OpenPauseComponent cleanup

### ISSUE THREAD

**Issue by IsaacGraham128** [UQdeco2800/2022-studio-2#296]
# **Description**
**Task:** [OpenPauseComponent cleanup](#296).
**Feature:** [Team 6 Code Optimisation, Clean Up and Testing](#262)

Clean up and complete testing of `OpenKeyBinds.java` involves `OpenPauseComponent.java` which has heavy involvement with Team 9. Changes to file and development of testing files will be done collaboratively.
 
# **Documentation**
- [Key Bind Implementation](https://github.com/UQdeco2800/2022-studio-2/wiki/Keybind-(Controls)-Page-Implementation)
 
# **Member**
- IsaacGraham (@IsaacGraham128)
- Yingzheng Cai (@Rey-666)

**Comment by IsaacGraham128** [comment]
Hi @Rey-666, I've cleaned up the playerGuide opening code and fixed that bug where the screens would darken each time a new player guide screen was opened!

**Comment by Rey-666** [comment]
> Hi @Rey-666, I've cleaned up the playerGuide opening code and fixed that bug where the screens would darken each time a new player guide screen was opened!

Cheers! Great work, thanx for helping out!
