### ISSUE TITLE
<Collaboration> Player Guide Locations

### ISSUE THREAD

**Issue by ew-b** [UQdeco2800/2022-studio-2#311]
# **Description**
**Task:** [Player Guide Locations](#308).
**Feature:** [Team 6 Code Optimisation, Clean Up and Testing #262] (https://github.com/UQdeco2800/2022-studio-2/issues/262)

Ensuring the locations in Player Guide maps are up to date so players know where to go when testing and using the game.
 
# **Documentation**
- [Player Guide](https://github.com/UQdeco2800/2022-studio-2/wiki/Player-Guide)

 
# **Member**
- Elias Blanch @Tired Camp Counsellor#6904 (@ew-b)
- Team 3 - Villans
- Team 7 - NPCs
- Team 9 - Crafting

**Comment by ew-b** [comment]
https://github.com/UQdeco2800/2022-studio-2/wiki/Placing-Enemies-On-Map provided by Caity

**Comment by lyphng** [comment]
Forest:
(100, 10) (47, 100) (96, 139) (144, 111)
Underground:
(36, 15) (11, 69) (49, 81) (90, 45)
r the coords for the crafting tables :)

**Comment by c-alsop** [comment]
> https://github.com/UQdeco2800/2022-studio-2/wiki/Placing-Enemies-On-Map provided by Caity

Yep, you should be able to find all the co-ordinates for the different enemies on there.

**Comment by ew-b** [comment]
Thank you everyone! I have updated the player guide's maps.
