### ISSUE TITLE
[Feature] Potions

### ISSUE THREAD

**Issue by cluanzon** [UQdeco2800/2022-studio-2#32]
# **Description**
The team plans to develop various potions and alchemic items, each of which gives the player the capability to either heal themselves, increase their defence and speed stats, or damage and destroy their enemies.

## SubFeature/component 
Potions are designed to help boost the player's character's values or reduce the enemy's attributes. For potions, there are some sub-features that are necessary

- Potions, as one of the important props for your character in the game, need to be stored in your character's inventory. Once the inventory has been built, we can place a variety of potions inside for players to pick and choose from.
- Outside of the inventory, characters need a common prop bar to equip basic potions. Setting up shortcuts helps players to use potions quickly without having to take them out of their inventory each time. It should be in the same place as the character's skills, spells, and base items. It is triggered by a bound quick button. This basic prop bar needs to be built in advance.
- In addition to the initial potions present in the inventory, additional potions can be found in treasure chests, corners and other hidden places in the map. You will need to pick the right coordinates to place the treasure chests with potions after the map has been built.
- Potions of the throwing type reduce the health or speed of the enemy. (Can only be obtained from treasure chests). When the effect of a potion is applied to an enemy. The enemy should also have a special animation around the model and a sound of the potion bottle breaking. Enemy model build required.

Armor/Robes/wands

- They can all be changed by changing the appearance of the character (clothing) to give the character different gaining effects.

Shield

- Shield effects require the addition of different coloured and looking apertures around the character's body to reflect the different roles of the shield. Depending on the properties of the shield, it may disappear when attacked.

## **Examples**
The player opens a chest to find a potion that they can choose to drink. 
- speed potion: increases player speed
- health potion: restores player health
- strength potion: increases player damage output
- mystery potion: gives a random buff, or inverts controls/player movement

# **Dependencies**

- Maps → We need to know the layout of the maps to be able to know where to store / hide the potions
- Players character customisation → We need to know how much max health / speed / stats the player will have to be able to determine how much we need to increase for each potion
- Inventory - We need to know how the various items we are responsible for will be interacted with in the inventory
- Skills - We need to know how our potions and other items will affect the players’ base stats and skills

# **Milestones**

**SPRINT 1**

**Week 4, Aug 19**
- [x] Implementing the overall design of the potions, as well as some base statistics for each one

**Week 5, Aug 23**
- Implementing ability to access inventory and select potions **(NOT COMPLETED)**

**Week 5, Aug 26**
- Implementing ability to quickly equip potions and use them through a hotbar **(NOT COMPLETED)**

**Week 5, Aug 28**
- Implementing loot system with potions found across the map, as well as having potions affect enemies as well **(NOT COMPLETED)**
 
**Completion Deadline:** Aug. 30

# **Extras**
- Mystery Potions that could have negative effects that inverts controls temporarily
- Spells and Magics
- Adaptive Soundtrack → When they drink the potion a different soundtrack can be added to inform the user that they are currently in buff mode (e.g 20s of Speed or 20s of increase attack speed).

# **Documentation**
- [Potions Design](https://github.com/UQdeco2800/2022-studio-2/wiki/Potions-Design)
- [Potion Code Logic](https://github.com/UQdeco2800/2022-studio-2/wiki/Potions-Code-Logic)
- [Potion Tests](https://github.com/UQdeco2800/2022-studio-2/wiki/Potions-test) 

# **Members**
- Chaitanya Dasi Luanzon (@cluanzon)
- Emily Southgate (@e-southgate)
- Enoe (Jolo) Gapusan (@jgapusan)
- Bokai Zhang (@hideonbush-crl)
- Jessica Froio (jessfroio)

**Comment by jgapusan** [comment]
ticket done ! @notalie @BozenX

**Comment by BozenX** [comment]
looks good!
