### ISSUE TITLE
JavaDoc Error showing in Main

### ISSUE THREAD

**Issue by LachlanBenson** [UQdeco2800/2022-studio-2#322]
## Description
Found error with JavaDoc publishing on latest main push made by Team05. 
![image](https://user-images.githubusercontent.com/109946739/196246558-096dd17e-0e79-4bee-981c-29875149a826.png)

Investigated error, found that there was an @return accidentally left on the comment of a function.
![image](https://user-images.githubusercontent.com/109946739/196246491-a2ce4381-fd2e-44ee-8fbf-4b9f87437a46.png)

Communicated findings to @rlybgithub

**Comment by LachlanBenson** [comment]
hey @rlybgithub just noticed a javadoc error on your latest push

Seems to be the @return in the function setGridPosition.

I've removed the @return now and re-pushed to main

Can you please verify this is now resolved?

**Comment by rlybgithub** [comment]
Hi Lanchanlan, that was a mistake, I just copied the Javadoc information from another method without deleting the return param, indeed there is no return on the set method🤣

Thank you so much for pointing out and fixing the issue, it looks good now!
![image](https://user-images.githubusercontent.com/109902711/196247659-87bcc61d-971e-4f08-9f2b-62a65b237796.png)

**Comment by LachlanBenson** [comment]
No worries! Hope you'll get a bit more sleep than I will be. ;)
